export { loremIpsum } from './strings/loremIpsum';
export { name } from './strings/name';
export { fromValues } from '../operations/fromValues';
export { age } from '../types/numbers/age';
export { arrayOf } from '../operations/arrayOf';
export { date } from './time/date';
export { image } from './images/image';
export { color } from './colors/color';
export { email } from './web/email';